
title: "DataBy AI Docs"
remote_theme: just-the-docs/just-the-docs # "mmistakes/minimal-mistakes@4.24.0"
logo: /assets/logo.svg
description: "Documentation for DataBy AI"

author: Mimi Phan
email: phan.mimi@outlook.com
timezone: "Australia/Sydney"
markdown: kramdown
highlighter: rouge
breadcrumbs: true
heading_anchors: false

url: https://whoamimi.github.io
baseurl: /databy-ai
repository: whoamimi/databy-ai

mermaid:
  version: "10.6.0"
  theme: "neo-dark"

toc: true
toc_label: "Content"
toc_icon: "cog"
toc_inline: true

sidebar:
  position: left
  title: "DataBy AI Docs"
  collapsible: true
  collapsed_by_default: false

aux_links:
  DataBy AI App:
    - https://databy.ai
  Github:
    - https://github.com/whoamimi/databy-ai
  Wordpress:
    - https://mimiphanblog.wordpress.com/
aux_links_position: top
aux_links_style: icons

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

navbar:
  title: "DataBy AI Docs"
  logo: /assets/logo.svg
  links:
    - title: "Home"
      url: /databy-ai/
      internal: true
    - title: "AI & Data Science"
      url: /databy-ai/pages/1_ai_agents/
      internal: true
  fixed: true
  collapsible: true
  collapsed_by_default: false
  show_downloads: true

footer_content: "Copyright &copy; 2025 DataBy AI. Distributed under the <a href=\"https://github.com/whoamimi/databy-ai/blob/main/LICENSE\">MIT License</a>."
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
gh_edit_link: false
gh_edit_repository: "https://github.com/whoamimi/databy-ai"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      comments: true
      share: true
      related: true