
title: "DataBy AI Docs"
remote_theme: mmistakes/minimal-mistakes
logo: /assets/logo.svg
description: "Documentation for DataBy AI"
minimal_mistakes_skin: "dark"

author: Mimi Phan
email: phan.mimi@outlook.com
timezone: "Australia/Sydney"
markdown: kramdown
highlighter: rouge
breadcrumbs: true
heading_anchors: false

url: https://whoamimi.github.io
baseurl: /databy-ai
repository: whoamimi/databy-ai

mermaid:
  version: "10.6.0"
  theme: "neo-dark"

toc: true
toc_label: "Content"
toc_icon: "cog"
classes: wide
header:
  title: "DataBy AI Documentation"
  logo: /assets/logo.svg
  tagline: "Blogs on building Autonomous AI Data Agent."

sidebar:
  nav: "docs"

aux_links:
  DataBy AI App:
    url: https://databy.ai
    icon: fas fa-robot
  Github:
    url: https://github.com/whoamimi/databy-ai
    icon: fab fa-github
  Wordpress:
    url: https://mimiphanblog.wordpress.com/
    icon: fas fa-blog

aux_links_position: top
aux_links_style: icons

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

navbar:
  title: "DataBy AI Docs"
  logo: /assets/logo.svg
  links:
    - title: "Home"
      url: /databy-ai/
      internal: true
    - title: "AI & Data Science"
      url: /databy-ai/pages/1_ai_agents/
      internal: true
  fixed: true
  collapsible: true
  collapsed_by_default: false
  show_downloads: true

footer_content: "Copyright &copy; 2025 DataBy AI. Distributed under the <a href=\"https://github.com/whoamimi/databy-ai/blob/main/LICENSE\">MIT License</a>."
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
gh_edit_link: false
gh_edit_repository: "https://github.com/whoamimi/databy-ai"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      comments: true
      share: true
      related: true