
title: "DataBy AI Docs"
remote_theme: mmistakes/minimal-mistakes
logo: /assets/logo.svg
color_scheme: light

author: Mimi Phan
email: phan.mimi@outlook.com
timezone: "Australia/Sydney"
markdown: kramdown
highlighter: rouge
breadcrumbs: true
heading_anchors: false
incremental: true
paginate: 10
enable_copy_code_button: true
inline_toc: true
pagination_previous: "Previous"
pagination_next: "Next"

url: https://whoamimi.github.io
baseurl: /databy-ai
repository: whoamimi/databy-ai

mermaid:
  version: "10.6.0"
  theme: "neo-dark"

show_downloads: true
defaults:
  -
    scope:
      path: "/pages"
      type: "docs"
    values:
      layout: "default"

sidebar:
  Home: index.md
  AI & Data Science: pages/1_ai_agents.md

aux_links:
  DataBy AI App:
    url: https://databy.ai
    icon: fas fa-robot
  Github:
    url: https://github.com/whoamimi/databy-ai
    icon: fab fa-github
  Wordpress:
    url: https://mimiphanblog.wordpress.com/
    icon: fas fa-blog
aux_links_position: top
aux_links_style: icons

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

footer_content: "Copyright &copy; 2025 DataBy AI. Distributed under the <a href=\"https://github.com/whoamimi/databy-ai/blob/main/LICENSE\">MIT License</a>."

